
services:
  php:
    build: /php
    ports:
      - "80:80"
    environment:
      - PHP_EXTENSIONS=mysqli
    volumes:
      - ./www:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
